-- ============================================
-- Supabase 迁移：创建 tools 表 + 导入初始数据
-- 在 Supabase SQL Editor 中执行
-- ============================================

-- 1. 建表
CREATE TABLE IF NOT EXISTS tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    rating SMALLINT DEFAULT 3 CHECK (rating >= 1 AND rating <= 5),
    comment TEXT DEFAULT '',
    detail TEXT DEFAULT '',
    tags TEXT[] DEFAULT '{}',
    slug TEXT DEFAULT '',
    color TEXT DEFAULT '#3B82F6',
    url TEXT DEFAULT '',
    download TEXT DEFAULT '',
    usage TEXT DEFAULT '',
    icon TEXT DEFAULT 'fa-cube',
    "iconUrl" TEXT DEFAULT '',
    is_custom BOOLEAN DEFAULT false,
    pinned BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. 插入 25 个初始工具
INSERT INTO tools (id, name, category, rating, comment, detail, tags, slug, color, url, download, usage, icon, pinned) VALUES
(1, 'VS Code', '开发工具', 5, '每天离不开的代码编辑器，插件生态无敌。', '微软出品的轻量级代码编辑器，内置 Git 支持、智能补全、调试器和海量扩展。无论是前端、后端还是全栈开发，VS Code 都能胜任。我已经用了 5 年，从 Sublime Text 转过来的，回不去了。插件生态是最大的优势，几乎任何语言或框架都能找到对应的扩展。', ARRAY['日常必备','免费'], 'visualstudiocode', '#007ACC', 'https://code.visualstudio.com/', 'https://code.visualstudio.com/Download', '推荐安装 Chinese 语言包、Prettier 和 ESLint 插件', 'fa-cube', false),
(2, 'Warp', '开发工具', 4, '现代化终端，AI 辅助和智能补全太香了。', '基于 Rust 构建的新一代终端，自带 AI 命令建议、智能补全和分屏功能。界面美观，输入体验流畅。最惊艳的是 AI 功能——输入自然语言描述，它会推荐对应的终端命令，对不熟悉命令行的人特别友好。', ARRAY['效率提升','免费'], 'warp', '#01A4FF', 'https://www.warp.dev/', 'https://www.warp.dev/download', '', 'fa-cube', false),
(3, 'GitHub Desktop', '开发工具', 4, '可视化 Git 操作，比命令行直观太多。', 'GitHub 官方出品的可视化 Git 客户端。对于不习惯命令行的开发者来说，它把 commit、push、pull、branch 切换、merge 等操作都变成了点击操作。与 GitHub 的集成非常紧密，查看 Pull Request、Issue 都很方便。', ARRAY['入门友好','免费'], 'github', '#18181b', 'https://desktop.github.com/', 'https://desktop.github.com/download/', '', 'fa-cube', false),
(4, 'Sourcetree', '开发工具', 3, '另一个 Git 客户端，分支管理很清晰。', 'Atlassian 出品的免费 Git 客户端。分支图谱可视化做得非常好，分支管理和冲突解决比 GitHub Desktop 更强大。', ARRAY['免费'], 'sourcetree', '#0052CC', 'https://www.sourcetreeapp.com/', '', '', 'fa-cube', false),
(5, 'Postman', '开发工具', 4, 'API 调试利器，团队协作功能也很强。', '最流行的 API 开发和测试工具。支持各种 HTTP 请求方式、环境变量管理、自动化测试脚本。团队协作功能可以共享 API 集合和文档。', ARRAY['必备','免费'], 'postman', '#FF6C37', 'https://www.postman.com/', 'https://www.postman.com/downloads/', '', 'fa-cube', false),
(6, 'Docker Desktop', '开发工具', 4, '容器化开发环境，再也不怕环境问题了。', 'Docker 官方桌面客户端，让容器化开发变得简单。一键创建、启动、管理容器，支持 Docker Compose。最大的好处是项目环境隔离。', ARRAY['必备'], 'docker', '#2496ED', 'https://www.docker.com/products/docker-desktop/', 'https://www.docker.com/products/docker-desktop/', '', 'fa-cube', false),
(7, 'iTerm2', '开发工具', 4, 'macOS 最强终端，分屏和配置都很赞。', 'macOS 上最流行的终端模拟器。分屏功能、热键窗口、丰富的配置选项让它远超系统自带的 Terminal。', ARRAY['macOS','免费'], '', '#1a1a2e', 'https://iterm2.com/', 'https://iterm2.com/downloads.html', '', 'fa-window-maximize', false),
(8, 'Figma', '设计工具', 5, '协作设计的天花板，UI/UX 设计首选。', '基于浏览器的协作式 UI 设计工具。天然支持多人实时协作——像 Google Docs 一样，设计师和开发可以同时在一个文件上工作。组件系统、自动布局和开发模式都是亮点。', ARRAY['日常必备','免费'], 'figma', '#F24E1E', 'https://www.figma.com/', '', '', 'fa-cube', false),
(9, 'Adobe Photoshop', '设计工具', 4, '图像处理的行业标准，功能无可替代。', '图像处理的行业标准，从照片修图到数字绘画，从 UI 设计到海报制作，Photoshop 几乎能做任何与图像相关的工作。', ARRAY['专业','付费'], 'adobephotoshop', '#31A8FF', 'https://www.adobe.com/products/photoshop.html', '', '', 'fa-cube', false),
(10, 'Adobe Illustrator', '设计工具', 4, '矢量设计标杆，Logo 和插画必备。', '矢量图形设计的标杆工具。Logo、图标、插画、排版设计的最佳选择。无限缩放不模糊。', ARRAY['专业','付费'], 'adobeillustrator', '#FF9A00', 'https://www.adobe.com/products/illustrator.html', '', '', 'fa-cube', false),
(11, 'Canva', '设计工具', 4, '快速出图的在线工具，非设计师也能用。', '在线设计平台，内置海量模板，社交媒体图片、演示文稿、海报等都能在几分钟内完成。', ARRAY['入门友好','免费'], 'canva', '#00C4CC', 'https://www.canva.com/', '', '', 'fa-cube', false),
(12, 'Unsplash', '设计工具', 4, '高质量免费图库，找素材第一站。', '全球最大的免费高质量图库。所有照片均可免费用于商业和非商业用途。API 接口也很方便。', ARRAY['免费','资源'], '', '#333333', 'https://unsplash.com/', '', '', 'fa-images', false),
(13, 'Notion', '效率工具', 5, '第二大脑，笔记/文档/项目管理全搞定。', 'All-in-one 的知识管理与协作平台。笔记、文档、数据库、看板、日历、Wiki 全部集成。最强大的是数据库功能——可以把任何页面变成结构化数据。', ARRAY['日常必备','免费'], 'notion', '#000000', 'https://www.notion.so/', '', '', 'fa-cube', true),
(14, 'Raycast', '效率工具', 5, 'macOS 效率启动器，比 Spotlight 强一百倍。', 'macOS 上的效率启动器。快速启动应用、文件搜索、剪贴板历史、计算器等。更厉害的是扩展生态——可以直接管理 Git 分支、搜索 Notion 页面等。', ARRAY['强烈推荐','免费','macOS'], 'raycast', '#FF6363', 'https://www.raycast.com/', '', '', 'fa-cube', false),
(15, 'Arc Browser', '效率工具', 4, '重新定义浏览器的使用方式，分屏太优雅。', '创新的浏览器。侧边栏标签管理和分屏功能——把浏览器重新想象成操作系统级别的工具。空间（Spaces）功能区分工作、个人场景。', ARRAY['强烈推荐','免费'], 'arc', '#FCBFBD', 'https://arc.net/', '', '', 'fa-cube', false),
(16, 'Obsidian', '效率工具', 4, '本地优先的知识管理，双向链接很强大。', '本地优先的知识管理工具，基于 Markdown 文件。双向链接和图谱视图是其核心特色。插件生态丰富，配合 Git 可免费多端同步。', ARRAY['免费','笔记'], 'obsidian', '#7C3FED', 'https://obsidian.md/', 'https://obsidian.md/download', '', 'fa-cube', false),
(17, 'Alfred', '效率工具', 4, '老牌效率工具，Workflow 功能无敌。', 'macOS 上老牌效率启动器。Workflow（工作流）是其独家优势——通过可视化编辑器创建自动化工作流。', ARRAY['macOS','付费'], 'alfred', '#5C5C5C', 'https://www.alfredapp.com/', '', '', 'fa-cube', false),
(18, 'Spotify', '日常工具', 5, '写代码的最佳伴侣，歌单推荐越来越懂我。', '全球最大的音乐流媒体平台。歌单推荐算法非常智能，Discover Weekly 每周都会推荐符合你口味的新歌。写代码时听 Lo-fi 或 Deep Focus 歌单。', ARRAY['日常必备','付费'], 'spotify', '#1DB954', 'https://www.spotify.com/', 'https://www.spotify.com/download', '', 'fa-cube', false),
(19, '1Password', '日常工具', 5, '密码管理，一个主密码管所有账号。', '最好的密码管理器之一。只需要记住一个主密码，其他所有账号密码都由 1Password 生成和管理。自动填充、跨设备同步。', ARRAY['强烈推荐','付费','安全'], '1password', '#3B66BC', 'https://1password.com/', 'https://1password.com/downloads', '', 'fa-cube', false),
(20, 'CleanShot X', '日常工具', 4, 'macOS 截图工具，滚动截图和录屏都好用。', 'macOS 上最好的截图和录屏工具。支持区域截图、窗口截图、滚动截图、录屏和 GIF 录制。标注功能也很强大。', ARRAY['macOS','付费'], '', '#3B82F6', 'https://cleanshot.com/', '', '', 'fa-camera', false),
(21, 'IINA', '日常工具', 4, 'macOS 上最好用的视频播放器，颜值和功能兼备。', 'macOS 上现代化的视频播放器，基于 mpv 引擎。支持几乎所有的视频格式，支持画中画、播放列表、字幕下载。开源免费。', ARRAY['macOS','免费','开源'], '', '#E91E63', 'https://iina.io/', 'https://iina.io/download', '', 'fa-film', false),
(22, 'Transmit', '日常工具', 3, '经典 FTP/SFTP 客户端，文件传输很稳定。', 'macOS 上经典的 FTP/SFTP 客户端。支持多连接管理、同步功能、磁盘挂载。传输速度快而稳定。', ARRAY['macOS','付费'], '', '#0D7A9E', 'https://panic.com/transmit/', '', '', 'fa-upload', false),
(23, 'Bartender', '系统工具', 4, '管理菜单栏图标，桌面整洁度提升 100%。', 'macOS 菜单栏管理工具。隐藏不常用的图标，只在需要时展开显示。让菜单栏保持整洁。', ARRAY['macOS','付费'], '', '#2563EB', 'https://www.macbartender.com/', '', '', 'fa-bars', false),
(24, 'Stats', '系统工具', 4, '免费的系统监控工具，一目了然。', 'macOS 上免费开源的系统监控工具。在菜单栏实时显示 CPU、内存、磁盘、网络、温度等系统状态。', ARRAY['macOS','免费','开源'], '', '#10B981', 'https://github.com/exelban/Stats', '', '', 'fa-chart-line', false),
(25, 'Hidden Bar', '系统工具', 3, '简单实用的菜单栏隐藏工具，开源免费。', 'Bartender 的免费开源替代品。功能简单直接——把不常用的菜单栏图标收起来，点击箭头展开。', ARRAY['macOS','免费','开源'], '', '#6B7280', 'https://github.com/dwarvesf/hidden', '', '', 'fa-eye-slash', false);

-- 3. 序列从 26 开始（1-25 已占用）
SELECT setval('tools_id_seq', 25, true);

-- 4. RLS 策略
-- SELECT 公开；INSERT/UPDATE/DELETE 需要 x-admin-token 请求头匹配 app.admin_token
-- 部署前在 Supabase SQL Editor 执行：SELECT set_config('app.admin_token', '你的强随机密钥', false);
-- Worker 的环境变量 SUPABASE_ADMIN_TOKEN 需与上述 set_config 的值一致
ALTER TABLE tools ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION is_admin() RETURNS boolean AS $$
BEGIN
  RETURN coalesce(current_setting('request.headers', true)::json->>'x-admin-token', '')
         = coalesce(current_setting('app.admin_token', true), '');
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE POLICY "public_read"  ON tools FOR SELECT USING (true);
CREATE POLICY "admin_write" ON tools FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "admin_update" ON tools FOR UPDATE USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "admin_delete" ON tools FOR DELETE USING (is_admin());

-- 5. 添加浏览量字段（后续迁移）
ALTER TABLE tools ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;

-- 6. 删除旧表（可选，确认迁移成功后再执行）
-- DROP TABLE IF EXISTS toolbox_data;

-- ============================================
-- 7. announcements 公告表
-- ============================================
CREATE TABLE IF NOT EXISTS announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'manual' CHECK (type IN ('manual','update','fix','add','delete')),
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
-- 公众可读；写入受 is_admin() 保护
CREATE POLICY "public_read"  ON announcements FOR SELECT USING (true);
CREATE POLICY "admin_write"  ON announcements FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "admin_update" ON announcements FOR UPDATE USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "admin_delete" ON announcements FOR DELETE USING (is_admin());


-- ============================================
-- 原子递增浏览量的 RPC 函数（避免竞态条件）
-- ============================================
CREATE OR REPLACE FUNCTION increment_tool_view(tool_id bigint) RETURNS integer AS $$
DECLARE
  new_views integer;
BEGIN
  UPDATE tools SET views = coalesce(views, 0) + 1 WHERE id = tool_id RETURNING views INTO new_views;
  RETURN new_views;
END;
$$ LANGUAGE plpgsql;
